name: Test Automation Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python main.py

      - name: Compare source and destination directories (Linux/macOS)
        if: matrix.os != 'windows-latest'
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            diff -qr /home/runner/automation_test/source /home/runner/automation_test/destiny
            if [ $? -ne 0 ]; then
              echo "Directories are different. Exiting..."
              exit 1
            fi
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            diff -qr /Users/runner/automation_test/source /Users/runner/automation_test/destiny
            if [ $? -ne 0 ]; then
              echo "Directories are different. Exiting..."
              exit 1
            fi
          fi

      - name: Compare source and destination directories (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          powershell -Command "
            $source = Get-ChildItem 'C:\Users\runneradmin\automation_test\source' -Recurse
            $destination = Get-ChildItem 'C:\Users\runneradmin\automation_test\destiny' -Recurse
            $result = Compare-Object -ReferenceObject \$source -DifferenceObject \$destination
            if ($result) {
              Write-Host 'Directories are different. Exiting...'
              exit 1
            }
          "
